CREATE TABLE users(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE pets(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    age INT DEFAULT 0,
    level_of_hunger REAL NOT NULL DEFAULT 100.0,
    level_of_thirst REAL NOT NULL DEFAULT 100.0,
    level_of_pollution REAL NOT NULL DEFAULT 100.0,
    level_of_fatigue REAL NOT NULL DEFAULT 100.0,
    mood REAL NOT NULL DEFAULT 100.0,
    last_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT REFERENCES users(id)
);